# Generated by Django 5.0.6 on 2024-06-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_stockdata_csvfile_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='date',
            field=models.DateField(),
        ),
    ]
