# Generated by Django 5.0.6 on 2024-06-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_csvfile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='close',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='high',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='low',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='open',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
